apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  namespace: web-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fwardzichowski/frontend:v1
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "backend-service/version"
        - name: BACKEND_PORT
          value: "5000"