apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net01
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
  namespace: student1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bridge-net01", 
    "plugins": [
        {
            "type": "cnv-bridge",
            "bridge": "br1",
            "macspoofchk": true,
            "vlan": 101,
            "preserveDefaultVlan": true
        },
        {
            "supportedVersions": [
                "0.3.0",
                "0.3.1",
                "0.4.0"
            ],
            "type": "opflex-agent-cni",
            "chaining-mode": true,
            "log-level": "debug",
            "log-file": "/var/log/netopcni.log"
        }
    ]
  }'