apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: vm1
  name: vm1
  namespace: studentX    # Replace X with your setup ID
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: vm1
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
            model: virtio
          - bridge: {}
            model: virtio
            name: nic-bridge-net01
            macAddress: 02:cf:f0:00:00:XX  # Replace XX with your setup ID, for single digit numbers use 01, 02, etc
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: bridge-net01
        name: nic-bridge-net01
      volumes:
      - dataVolume:
          name: vm1
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cisco
            password: clams24
            chpasswd: { expire: False }
          networkData: |-
            version: 2
            ethernets:
              eth1:
                match:
                  macaddress: 02:cf:f0:00:00:XX   # Replace XX with your setup ID, for single digit numbers use 01, 02, etc
                addresses:
                  - 192.168.2XX.11/24    # Replace XX with your setup ID, for single digit numbers use 01, 02, etc
        name: cloudinitdisk
